## Mod Properties

# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the regex [a-z][a-z0-9_]{1,63}
# Must match the String constant located in the main mod class annotated with @Mod.
mod_id=dismount_rebind
# The human-readable display name for the mod.
mod_name=Dismount Rebind
# The license of the mod.
mod_license=MIT
# The mod version.
mod_version=1.0.2
# The group ID for the mod. It is only important when publishing as an artifact to a Maven repository.
mod_group_id=com.dismountrebind
# The authors of the mod.
mod_authors=spork
# The description of the mod.
mod_description=Adds a separate, rebindable Dismount key, decoupling dismounting from the Sneak key.

# This mod uses Mixin.
use_mixin=true
